ALTER TABLE leads ADD COLUMN IF NOT EXISTS validation_status TEXT;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS disposable BOOLEAN;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS role_based BOOLEAN;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS free_provider BOOLEAN;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS risk_score INTEGER;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS suggestion TEXT;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS mx_records TEXT[];
ALTER TABLE leads ADD COLUMN IF NOT EXISTS provider TEXT;
